name: Audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - '**/yarn.lock'
      - '**/package.json'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn audit
        run: yarn audit
